### PR TITLE
Improve entry and exit of modal

### PR DESCRIPTION
**Pull request by superandrew213**
I thought that the entry of the modal is fine but the backdrop abruptly appears. The exit of the modal and backdrop both abruptly disappear.

Let me know what you think.

### CODE REVIEW

**Comment by feyy** [comment]
Thanks for your PR. I will handle it in this week later. Sorry!

**Comment by superandrew213** [comment]
Sure no problem

**Comment by feyy** [comment]
I think the animation will give me the sense of slow(`duration` is control the slide animation indeed). And I think the animation of the panel is enough. Meanwhile the animation of modal is not easy to control. How do you think?

**Comment by superandrew213** [comment]
Yes modal animation is not easy to control but I think "fade" does a good enough job. I think having a consistent entry and exit is important. Right now it doesn't match and looks choppy.

What the PR does:
Entry: Fade in modal/backdrop and animate datepicker into view.
Exit: Animate datepicker out of view and fade out modal/backdrop.

Looks more consistent with the IOS experience. But it's up to you if you want to include it or not.

**Comment by superandrew213** [comment]
@feyy There is also this [react-native-modalbox](https://github.com/maxs15/react-native-modalbox) which could handle all the animation work.

**Pull request closed without merging**
