### PR TITLE
feat: add `getDateStr` prop to customize display outside `moment` format

### PR DESCRIPTION
**Pull request by blackxored**

### CODE REVIEW

**Comment by vnglst** [comment]
This is great, exactly what I was looking for myself. Maintainers (@feyy @atlanteh), is there anyway I can help speed up the process of merging this? It think it solves two important issues with localization:

1) The iOS Datepicker is currently not localized at all (always in English, even if system language is otherwise)
2) Localization requires Moment.js, but in our project we're using React-Intl. It would be great to be able to use their interface instead.

Both issues are valid for React Native 0.52. Just tested them with the latest basic RN starter app. If it helps I can create these issues in the Issues tab.

**Comment by atlanteh** [comment]
I'm no maintainer.. I created a PR once, more that a year ago 😀

**Comment by vnglst** [comment]
@atlanteh haha, thanks for responding anyway! 👍

**Comment by feyy** [comment]
I'm so sorry for that! Thanks for your great contribution.

**Pull request merged**
