### PR TITLE
Added an option to disable the Date Text and update the README

### PR DESCRIPTION
**Pull request by avencat**
Added an option to disable the TextInput (hideText), added it to the README and fixed the README array

### CODE REVIEW

**Comment by feyy** [comment]
Thanks very much! But you can hide the text with style. Can your update the readme with another issue and using markdown only? Or I'll fix by myself.

**Comment by avencat** [comment]
Hi @feyy ! I've had some issue when trying to hide the icon with style only where the border stayed ! ;) So I managed to do this, it was the only way for me to disable the dateText... (I also followed #117)

**Comment by avencat** [comment]
@feyy Here what I get with:
```javascript
customStyles={{
  dateInput: {
    borderStyle: null,
    height: 0,
    width: 0,
  }
}}
```

capture d ecran 2017-05-24 a 11 17 37


(I still get the little dot at the left)

But with this PR, as the textInput won't render anymore, I will be able to delete this little dot.

Is this possible to merge it ?

**Comment by avencat** [comment]
Hi! I've upgraded to react-native v0.45 and it seems that you can't hide the text with style anymore. Can you confirm that?

I get this:
capture d ecran 2017-06-07 a 19 23 36

with this style:
```javascript
dateInput: {
  borderWidth: 0,
  borderStyle: null,
  height: 0,
  width: 0,
},
```

**Comment by avencat** [comment]
@feyy I've tested this PR on RN v0.45 and it works well. Could you merge this please ?

**Pull request merged**
