### PR TITLE
add placeholder when this.props.date is missing

### PR DESCRIPTION
**Pull request by atlanteh**
Hi, I added a placeholder prop to show in case you don't want to supply a default date and want a friendly message to show to user.
I also think we might want to have different styles for the placeholder and date. what do you think?

### CODE REVIEW

**Comment by feyy** [comment]
It's a good feature. But there are some problems need to be solved.
1. The placeholder only show when `props.date` is undefined or ''... Then the picker can't run properly anymore. Or we can set an inner flag to show the placeholder default when `placeholder` is provided?
2. We should give some default style for placeholder.

**Comment by atlanteh** [comment]
Thx :)
1. I think the placeholder is supposed to be shown only if no date is provided. If a date is provided, the provided date is supposed to be shown. no? why can't the picker run properly anymore.. it seems to run fine on my android.
2. I'll add that too.

**Comment by atlanteh** [comment]
Anything else you need here? If not, can u please merge?

**Comment by feyy** [comment]
Ok! Will handle it Tonight！

**Comment by anton6** [comment]
Hi, this is very helpful feature.
Can you please push this to npm when you get the chance? 
Thanks.

**Pull request merged**
